//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lech_Poznań.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LechPoznanEntities : DbContext
    {
        public LechPoznanEntities()
            : base("name=LechPoznanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Funckje> Funckjes { get; set; }
        public virtual DbSet<Nagrody> Nagrodies { get; set; }
        public virtual DbSet<Nagrody_dla_sztabu> Nagrody_dla_sztabus { get; set; }
        public virtual DbSet<Nagrody_dla_zawodników> Nagrody_dla_zawodników { get; set; }
        public virtual DbSet<Pozycje> Pozycjes { get; set; }
        public virtual DbSet<Sztab> Sztabs { get; set; }
        public virtual DbSet<Zawodnicy> Zawodnicies { get; set; }
    }
}
