//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lech_Poznań.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nagrody
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nagrody()
        {
            this.Nagrody_dla_sztabu = new HashSet<Nagrody_dla_sztabu>();
            this.Nagrody_dla_zawodników = new HashSet<Nagrody_dla_zawodników>();
        }
    
        public int Id_Nagrody { get; set; }
        public string Nagroda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nagrody_dla_sztabu> Nagrody_dla_sztabu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nagrody_dla_zawodników> Nagrody_dla_zawodników { get; set; }
    }
}
