//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lech_Poznań.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nagrody_dla_zawodników
    {
        public int IdNZ { get; set; }
        public Nullable<int> Id_Zawodnika { get; set; }
        public Nullable<int> Id_Nagrody { get; set; }
    
        public virtual Nagrody Nagrody { get; set; }
        public virtual Zawodnicy Zawodnicy { get; set; }
    }
}
