//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lech_Poznań.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class Zawodnicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zawodnicy()
        {
            this.Nagrody_dla_zawodników = new HashSet<Nagrody_dla_zawodników>();
        }
    
        public int Id_Zawodnika { get; set; }
        public string Imię { get; set; }
        public string Nazwisko { get; set; }
        public Nullable<int> Wiek { get; set; }
        public Nullable<int> Id_Pozycji { get; set; }
        [DisplayName("Ilość występów")]
        public Nullable<int> Ilość_występów { get; set; }
        [DisplayName("Strzelone gole")]
        public Nullable<int> Strzelone_gole { get; set; }
        public Nullable<int> Asysty { get; set; }
        [DisplayName("Czyste konta")]
        public int Czyste_konta { get; set; }
        [DisplayName("Zdjęcie")]
        public string Zdjęcie { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nagrody_dla_zawodników> Nagrody_dla_zawodników { get; set; }
        public virtual Pozycje Pozycje { get; set; }

        public string FullName
        {
            get
            {
                return String.Format("{0} {1}", Imię, Nazwisko);
            }
        }
    }
}
